repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.0
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi, jupyter]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
  - repo: https://github.com/TomWright/dasel
    rev: v2.8.1
    hooks:
      - id: dasel-validate

  - repo: local
    hooks:
      - id: test
        name: Run tests
        entry: just test
        language: system
        pass_filenames: false
        always_run: true
