# To boot the app run the following:
# docker compose run auto-gpt
# NOTE: Version 3.9 requires at least Docker Compose version 2 and Docker Engine version 20.10.13!

version: "3.9"

services:
  bot:
    build: .
    volumes:
      - ./:/app
    ports:
      - 8888:8888
